### PR TITLE
Add Validated in standard

### PR DESCRIPTION
**Pull request by fteychene**
Add Validated in standard with pure and apply

### CODE REVIEW

**Comment by gr-im** [comment]
To be honest, not being very comfortable with Kotlin, and that the code is very complicated (for a layman; I'm not implying that it's your fault) but I don't feel that the semantics of "Validate" are correct. Generally, the opposition between Result and Validate is that the right-hand type of Validate is a traversable construct (commonly, a non-empty list) and respects the interface of a Semigroup, to accumulate errors (unlike Result).

**Comment by gr-im** [comment]
(So a quick fix is only renaming Validation into Result)

**Comment by d-plaindoux** [comment]
Agree! The proposed construction is not the appropriate one for Validated. If you change it to Result the corresponding monad can also be defined.

Reference: https://typelevel.org/cats/datatypes/validated.html
Reference: https://hackage.haskell.org/package/validation-1.1.1/docs/Data-Validation.html

**Comment by fteychene** [comment]
Agreeing with the missing behaviour, as some other pieces wasn't implemented yet.
Closing this issue, it was maily to try how to add a a struct in standard

**Pull request closed without merging**
